
### 获取用户列表

POST http://127.0.0.1:56565/api/user/detail
Content-Type: application/json

{
    "qrcodeName": 11
}


### 获取用户详细信息
POST http://127.0.0.1:56565/api/user/getWord
Content-Type: application/json


